"""Generate the six phase explanation notebooks."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks"

SETUP = """\
import sys
from pathlib import Path

# Run from notebooks/ — project root is one level up
ROOT = Path.cwd()
if not (ROOT / "shared").exists() and (ROOT.parent / "shared").exists():
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

print(f"Project root: {ROOT.resolve()}")
"""

NOTEBOOKS: list[tuple[str, list[dict]]] = [
    (
        "01_multimodal_ingestion",
        [
            {
                "type": "markdown",
                "source": """# Phase 1 — Multimodal Ingestion

**Weeks 1–3 · Goal:** Ingest text, tables, figures, and page images from PDFs into Qdrant with modality-specific embeddings.

## What you will learn

- How PDFs become typed **chunks** (`text`, `table`, `figure`, `page_image`)
- Why each chunk type gets its own **Qdrant collection** and embedding model
- How **Reciprocal Rank Fusion (RRF)** merges results across collections at query time
- The unified entry point: `RAGPipeline` in `shared/pipeline.py`

> **Code:** `phases/phase_01_multimodal_ingestion/` · **Demo CLI:** `phases/phase_01_multimodal_ingestion/demo.py`
""",
            },
            {"type": "code", "source": SETUP},
            {
                "type": "markdown",
                "source": """## Architecture

```
PDF ──► Parsers ──► DocumentChunks ──► embed_chunks() ──► Qdrant
         │ text/table/figure/page          │ bge-m3 / CLIP / ColPali
         └─────────────────────────────────┴──► 4 collections
```

| Parser | Chunk type | Collection | Embedder |
|--------|------------|------------|----------|
| `PDFTextParser` | `text` | `text_chunks` | bge-m3 (1024-d) |
| `TableParser` | `table` | `table_chunks` | bge-m3 |
| `FigureParser` | `figure` | `figure_chunks` | CLIP (512-d) |
| `PageImageParser` | `page_image` | `page_chunks` | bge-m3 or ColPali (128-d) |
""",
            },
            {
                "type": "code",
                "source": """from shared.models import ChunkType
from phases.phase_01_multimodal_ingestion.stores.qdrant_store import COLLECTION_MAP

for chunk_type, collection in COLLECTION_MAP.items():
    print(f"{chunk_type.value:12} → {collection}")
""",
            },
            {
                "type": "markdown",
                "source": """## Inspect parsers (no Qdrant required)

The sample report PDF is generated by `scripts/generate_sample_report.py`. If it exists, we parse it locally and count chunk types.
""",
            },
            {
                "type": "code",
                "source": """from collections import Counter

from phases.phase_01_multimodal_ingestion.parsers.figure_parser import FigureParser
from phases.phase_01_multimodal_ingestion.parsers.page_image_parser import PageImageParser
from phases.phase_01_multimodal_ingestion.parsers.pdf_text_parser import PDFTextParser
from phases.phase_01_multimodal_ingestion.parsers.table_parser import TableParser

sample = ROOT / "data/raw/sample_report.pdf"
if not sample.exists():
    print("Run: python scripts/generate_sample_report.py")
else:
    parsers = [PDFTextParser(), TableParser(), FigureParser(), PageImageParser()]
    chunks = []
    for p in parsers:
        chunks.extend(p.parse(sample))
    counts = Counter(c.chunk_type.value for c in chunks)
    print(f"Parsed {len(chunks)} chunks from {sample.name}:")
    for kind, n in sorted(counts.items()):
        print(f"  {kind}: {n}")
    print("\\nExample chunk:")
    print(chunks[0].model_dump(exclude={"metadata"}))
""",
            },
            {
                "type": "markdown",
                "source": """## Ingest + retrieve (requires Qdrant)

Start Qdrant: `cd docker && docker compose up -d qdrant`

Then ingest and run a retrieval-only query (no LLM needed).
""",
            },
            {
                "type": "code",
                "source": """from shared.models import QueryRequest
from shared.pipeline import PipelineConfig, RAGPipeline

sample = ROOT / "data/raw/sample_report.pdf"
if not sample.exists():
    print("Missing sample PDF — skip ingest demo")
else:
    try:
        cfg = PipelineConfig(text_only=True, use_hybrid=False)
        pipe = RAGPipeline(config=cfg)
        result = pipe.ingest(str(sample))
        print(f"Ingested {result.chunks_upserted} chunks → doc_id={result.doc_id}")

        resp = pipe.query(
            QueryRequest(
                query="What does Figure 3 show about revenue trends?",
                doc_id=result.doc_id,
                top_k=5,
                retrieve_only=True,
            )
        )
        for i, ctx in enumerate(resp.contexts[:3], 1):
            print(f"{i}. [{ctx.chunk_type}] p{ctx.page_number} score={ctx.score:.3f}")
            print(f"   {ctx.content[:120]}...")
    except Exception as exc:
        print(f"Qdrant or models unavailable: {exc}")
""",
            },
            {
                "type": "markdown",
                "source": """## Key concepts

1. **Modality routing** — Questions about charts route to `figure_chunks`; table questions to `table_chunks` via query hints + RRF weights.
2. **Dimension safety** — `page_chunks` must match ingest mode (ColPali 128-d vs bge-m3 1024-d); see `page_index_status()`.
3. **Single pipeline** — Phase 1 demo, eval, and API all call `RAGPipeline`.

**Next:** [02_long_doc_retrieval.ipynb](02_long_doc_retrieval.ipynb) — hybrid search and long-document chunking.
""",
            },
        ],
    ),
    (
        "02_long_doc_retrieval",
        [
            {
                "type": "markdown",
                "source": """# Phase 2 — Long-Document Retrieval

**Weeks 4–6 · Goal:** Retrieve the right pages from 200+ page PDFs using better chunking, hybrid search, and reranking.

## What you will learn

- **Section paths** — breadcrumb context prepended before embedding (`2 > Financial Results > Revenue`)
- **Recursive vs semantic chunking** — split long text without losing coherence
- **Hybrid retrieval** — BM25 sparse + dense vectors fused with RRF (text collection only)
- **Parent expand** — retrieve small child chunks, return full parent context
- **FlashRank** — fast cross-encoder reranking alternative to Phase 1 reranker

> Phase 1 multimodal paths (figures, tables, ColPali pages) are unchanged; Phase 2 enhances **text** retrieval.
""",
            },
            {"type": "code", "source": SETUP},
            {
                "type": "markdown",
                "source": """## Feature flags

All features are toggled via `PipelineConfig` or CLI flags on `demo.py`:

| Feature | Config / flag | When |
|---------|---------------|------|
| Recursive chunker | `use_recursive_chunker` / `--recursive-chunk` | Ingest |
| Semantic chunker | `use_semantic_chunker` / `--semantic-chunk` | Ingest |
| Section paths | `use_section_paths` (default on) | Ingest |
| Context enrichment | `use_context_enrichment` (default on) | Ingest |
| Hybrid BM25+dense | `use_hybrid` / `--hybrid` | Query |
| Parent expand | `use_parent_expand` (default on) | Query |
| FlashRank | `use_flashrank` / `--flashrank` | Query |
""",
            },
            {
                "type": "code",
                "source": """from phases.phase_02_long_doc_retrieval.chunking.recursive_chunker import RecursiveChunker
from shared.models import ChunkType, DocumentChunk, DocumentType

# Synthetic long section — recursive chunker splits on paragraph/sentence boundaries
long_text = "Configuration management baseline.\\n\\n" + ("A baseline is a specification approved for use. " * 40)
parent = DocumentChunk(
    id="parent-1",
    doc_id="demo",
    source_path="demo.pdf",
    doc_type=DocumentType.PDF,
    chunk_type=ChunkType.TEXT,
    content=long_text,
    page_number=42,
    section_path="3 > Configuration Management > Baselines",
)
chunker = RecursiveChunker(chunk_size=200, chunk_overlap=30)
children = chunker.chunk([parent])
print(f"Split 1 parent chunk into {len(children)} children")
print(f"First child section_path: {children[0].section_path}")
print(f"First child preview: {children[0].content[:100]}...")
""",
            },
            {
                "type": "code",
                "source": """from phases.phase_02_long_doc_retrieval.retrieval.hybrid_retriever import reciprocal_rank_fusion
from shared.models import ChunkType, DocumentChunk, DocumentType, RetrievalStrategy, RetrievedContext

def _ctx(chunk_id: str, content: str, rank: int) -> RetrievedContext:
    chunk = DocumentChunk(
        id=chunk_id,
        doc_id="demo",
        source_path="demo.pdf",
        doc_type=DocumentType.PDF,
        chunk_type=ChunkType.TEXT,
        content=content,
    )
    return RetrievedContext(chunk=chunk, score=1.0 / rank, strategy=RetrievalStrategy.HYBRID, rank=rank)

# RRF merges ranked lists from BM25 and dense search
sparse = [_ctx("c3", "margin table", 1), _ctx("c1", "revenue", 2), _ctx("c4", "footer", 3)]
dense = [_ctx("c1", "revenue", 1), _ctx("c2", "summary", 2), _ctx("c3", "margin table", 3)]
fused = reciprocal_rank_fusion([sparse, dense], k=60)
print("Fused ranking (higher score = better):")
for ctx in fused[:4]:
    print(f"  {ctx.chunk.id}: {ctx.score:.4f}")
""",
            },
            {
                "type": "markdown",
                "source": """## Try on a long document

Use `data/raw/long_report.pdf` (812-page textbook) with hybrid + recursive chunk:

```bash
python phases/phase_01_multimodal_ingestion/demo.py \\
  --doc data/raw/long_report.pdf \\
  --query "What is a baseline in configuration management?" \\
  --hybrid --recursive-chunk --retrieve-only
```
""",
            },
            {
                "type": "code",
                "source": """from shared.models import QueryRequest
from shared.pipeline import PipelineConfig, RAGPipeline

# Short demo on sample_report.pdf (long_report.pdf works the same with --hybrid --recursive-chunk)
sample = ROOT / "data/raw/sample_report.pdf"
if not sample.exists():
    print("Run: python scripts/generate_sample_report.py")
else:
    try:
        cfg = PipelineConfig(
            text_only=True,
            use_hybrid=True,
            use_recursive_chunker=True,
            use_section_paths=True,
            use_parent_expand=True,
        )
        pipe = RAGPipeline(config=cfg)
        ing = pipe.ingest(str(sample))
        resp = pipe.query(
            QueryRequest(
                query="What was Q4 2024 revenue and operating margin?",
                doc_id=ing.doc_id,
                top_k=5,
                retrieve_only=True,
            )
        )
        print(f"Hybrid retrieval returned {len(resp.contexts)} contexts")
        for ctx in resp.contexts[:3]:
            print(f"  p{ctx.page_number} [{ctx.chunk_type}] {ctx.content[:80]}...")
    except Exception as exc:
        print(f"Requires Qdrant: {exc}")
""",
            },
            {
                "type": "markdown",
                "source": """**Next:** [03_scalable_ingestion.ipynb](03_scalable_ingestion.ipynb) — bulk ingest at scale with Celery and Redis caching.
""",
            },
        ],
    ),
    (
        "03_scalable_ingestion",
        [
            {
                "type": "markdown",
                "source": """# Phase 3 — Scalable Ingestion

**Weeks 7–9 · Goal:** Ingest hundreds of PDFs efficiently with caching, deduplication, and observability.

## What you will learn

- **Embedding cache** — Redis stores vectors keyed by content fingerprint (skip re-embed on unchanged chunks)
- **Document fingerprint** — skip entire PDFs when file hash unchanged
- **MinHash dedup** — near-duplicate chunk detection before upsert
- **Celery workers** — async ingest queue for bulk jobs
- **Prometheus metrics** — throughput, latency, cache hit rate on `:9100/metrics`

> **Code:** `phases/phase_03_scalable_ingestion/`
""",
            },
            {"type": "code", "source": SETUP},
            {
                "type": "markdown",
                "source": """## Ingest modes

`IngestMode` controls parser/embedding cost:

| Mode | Parsers | Use case |
|------|---------|----------|
| `TEXT_ONLY` | text + tables | Fast bulk indexing |
| `MULTIMODAL` | + figures + pages | Full multimodal |
| `COLPALI` | + ColPali page embeds | GPU page-level retrieval |
""",
            },
            {
                "type": "code",
                "source": """from phases.phase_03_scalable_ingestion.pipeline.ingest_modes import IngestMode, build_ingestion_pipeline

for mode in IngestMode:
    pipeline = build_ingestion_pipeline(mode)
    parser_names = [type(p).__name__ for p in pipeline.parsers]
    print(f"{mode.value:12} parsers: {parser_names}")
""",
            },
            {
                "type": "code",
                "source": """from phases.phase_03_scalable_ingestion.embedding.fingerprint import chunk_embed_key, doc_fingerprint
from shared.models import ChunkType, DocumentChunk, DocumentType

chunk = DocumentChunk(
    id="c1",
    doc_id="d1",
    source_path="x.pdf",
    doc_type=DocumentType.PDF,
    chunk_type=ChunkType.TEXT,
    content="Revenue grew 15% year-over-year.",
    page_number=1,
)
print("Chunk embed key:", chunk_embed_key(chunk))
print("Doc fingerprint:", doc_fingerprint(ROOT / "README.md"))
""",
            },
            {
                "type": "code",
                "source": """# Redis cache demo (requires Redis on localhost:6379)
try:
    from phases.phase_03_scalable_ingestion.embedding.redis_cache import EmbeddingCache

    cache = EmbeddingCache()
    content_hash = "demo123"
    cache.set_vector(content_hash, "bge-m3", [0.1, 0.2, 0.3])
    hit = cache.get_vector(content_hash, "bge-m3")
    print(f"Cache hit: {hit is not None}, dim={len(hit) if hit else 0}")
except Exception as exc:
    print(f"Redis unavailable ({exc}). Start: cd docker && docker compose up -d redis")
""",
            },
            {
                "type": "markdown",
                "source": """## Bulk ingest CLI

```powershell
cd docker
docker compose --profile phase3 up -d qdrant redis ingest-worker
docker compose exec ingest-worker python phases/phase_03_scalable_ingestion/bulk_ingest.py \\
  --glob "data/raw/bulk/*.pdf" --sync --text-only --hybrid --recursive-chunk
```

Generate 100 test PDFs: `python scripts/generate_bulk_pdfs.py --count 100`

**Next:** [04_taxonomy_generation.ipynb](04_taxonomy_generation.ipynb)
""",
            },
        ],
    ),
    (
        "04_taxonomy_generation",
        [
            {
                "type": "markdown",
                "source": """# Phase 4 — Taxonomy & Conformity Validation

**Weeks 10–12 · Goal:** Validate LLM answers against a classification ontology (allowed vs forbidden labels).

## What you will learn

- Loading an **RDF/Turtle** taxonomy (`data/taxonomies/classification.ttl`)
- **Entity extraction** — find classification terms in queries and answers
- **Fuzzy linking** — map typos to canonical labels with rapidfuzz
- **Conformity scoring** — flag forbidden labels (e.g. `SECRET-TOP-SECRET`)
- Pipeline hook — every `RAGPipeline.query()` can attach conformity metadata

> Used in production API responses as `metadata.conformity`.
""",
            },
            {"type": "code", "source": SETUP},
            {
                "type": "code",
                "source": """from phases.phase_04_taxonomy_generation.ontology.loader import load_taxonomy

ttl = ROOT / "data/taxonomies/classification.ttl"
tax = load_taxonomy(ttl)
print("Allowed labels:", tax.allowed_labels[:5], "...")
print("Forbidden labels:", tax.forbidden_labels[:5], "...")
""",
            },
            {
                "type": "code",
                "source": """from phases.phase_04_taxonomy_generation.linking.entity_extractor import extract_classification_terms

text = "Please classify this document as SECRET-TOP-SECRET for internal review."
terms = extract_classification_terms(text)
print("Extracted terms:", terms)
""",
            },
            {
                "type": "code",
                "source": """from phases.phase_04_taxonomy_generation.validation.conformity_validator import ConformityValidator

validator = ConformityValidator()
for query, answer in [
    ("Classify as INTERNAL", "This document is INTERNAL."),
    ("Classify as SECRET-TOP-SECRET", "The classification is SECRET-TOP-SECRET."),
    ("Classify as SECRET-TOP-SECRET", "I cannot classify this as SECRET-TOP-SECRET; allowed labels are PUBLIC, INTERNAL, CONFIDENTIAL."),
]:
    result = validator.validate(query=query, answer=answer)
    print(f"Q: {query[:40]}...")
    print(f"   score={result.score:.2f} flagged={result.flagged} reason={result.reason[:60] if result.reason else '-'}")
    print()
""",
            },
            {
                "type": "markdown",
                "source": """## Block forbidden answers

Set `block_forbidden_classifications=True` in `PipelineConfig` to replace non-compliant answers with a refusal message.

**Next:** [05_evaluation.ipynb](05_evaluation.ipynb)
""",
            },
        ],
    ),
    (
        "05_evaluation",
        [
            {
                "type": "markdown",
                "source": """# Phase 5 — Evaluation

**Weeks 13–15 · Goal:** Measure retrieval and answer quality on a golden Q&A set with HTML reports and regression baselines.

## What you will learn

- **Golden set** — `data/benchmarks/golden_qa.json` (15 samples across sample + long docs)
- **Retrieval metrics** — page recall, chunk-type recall, keyword recall
- **Answer metrics** — faithfulness heuristics, keyword overlap, optional RAGAS
- **HTML reports** — human-readable eval summaries in `phases/phase_05_evaluation/reports/`
- **Baselines** — compare runs and alert on regressions

> Run retrieval-only eval without an LLM — ideal for CI.
""",
            },
            {"type": "code", "source": SETUP},
            {
                "type": "code",
                "source": """import json

golden_path = ROOT / "data/benchmarks/golden_qa.json"
samples = json.loads(golden_path.read_text(encoding="utf-8"))
print(f"Golden set: {len(samples)} samples")
tags = {}
for s in samples:
    tags[s.get("tag", "untagged")] = tags.get(s.get("tag", "untagged"), 0) + 1
print("By tag:", tags)
print("\\nExample sample:")
print(json.dumps(samples[0], indent=2)[:500], "...")
""",
            },
            {
                "type": "code",
                "source": """from phases.phase_05_evaluation.metrics import compute_sample_metrics, sample_passed
from shared.models import EvalResult, MetricScore

# Illustrative metric computation on a fake result
fake = EvalResult(
    sample_id="demo",
    query="What was Q4 revenue?",
    generated_answer="",
    ground_truth_answer="$191.7M",
    retrieved_chunk_ids=["c1"],
    metrics=[
        MetricScore(name="retrieval_page_recall", value=1.0),
        MetricScore(name="latency_ms", value=95.0),
    ],
    passed=True,
    latency_ms=95.0,
)
print("Sample passed:", sample_passed(fake.metrics, require_answer=False))
""",
            },
            {
                "type": "markdown",
                "source": """## Run full evaluation

```bash
python phases/phase_05_evaluation/run_full_eval.py \\
  --system phase_02 --retrieve-only --hybrid --recursive-chunk \\
  --ingest-if-missing --tag long-doc
```

Open the generated HTML report under `phases/phase_05_evaluation/reports/`.

**Next:** [06_production_api.ipynb](06_production_api.ipynb)
""",
            },
        ],
    ),
    (
        "06_production_api",
        [
            {
                "type": "markdown",
                "source": """# Phase 6 — Production API

**Weeks 16–18 · Goal:** Ship DocuMind as a production FastAPI service with guardrails and observability.

## What you will learn

- **FastAPI routes** — `/query`, `/ingest`, `/admin/*`, `/health`, `/metrics`
- **PII redaction** — Microsoft Presidio on queries, answers, and ingest text
- **Rate limiting** — slowapi per-IP limits
- **OpenTelemetry** — distributed traces to Jaeger
- **DocuMind Web** — React frontend on port 5174 proxying `/api` → `rag-api`

> **ASGI app:** `phases.phase_06_production.api.main:app` or `documind.production.app`
""",
            },
            {"type": "code", "source": SETUP},
            {
                "type": "code",
                "source": """from phases.phase_06_production.api.main import app

routes = sorted({r.path for r in app.routes if hasattr(r, "methods")})
print("Registered routes:")
for path in routes:
    print(f"  {path}")
""",
            },
            {
                "type": "code",
                "source": """from phases.phase_06_production.guardrails.pii import PIIRedactor

redactor = PIIRedactor()
text = "Contact john.doe@example.com or call 555-123-4567 about Q4 results."
clean, changed = redactor.redact(text)
print("Original:", text)
print("Redacted:", clean)
print("Changed:", changed)
""",
            },
            {
                "type": "code",
                "source": """# Live API smoke test (requires: docker compose --profile production up -d rag-api)
import os
import httpx

API = os.environ.get("RAG_API_URL", "http://localhost:8002")
try:
    r = httpx.get(f"{API}/health", timeout=5.0)
    print(f"Health: {r.status_code} {r.json()}")
    ready = httpx.get(f"{API}/ready", timeout=10.0)
    print(f"Ready:  {ready.status_code} {ready.json()}")
except Exception as exc:
    print(f"API offline at {API}: {exc}")
    print("Start: cd docker && docker compose --profile production up -d qdrant redis rag-api")
""",
            },
            {
                "type": "markdown",
                "source": """## Production stack

| Service | URL | Role |
|---------|-----|------|
| DocuMind Web | http://localhost:5174 | React UI + nginx `/api` proxy |
| RAG API | http://localhost:8002 | FastAPI backend |
| Jaeger | http://localhost:16686 | Trace UI |
| Grafana | http://localhost:3000 | Dashboards (admin/admin) |

## Capstone integration

- **CLI:** `documind ingest --doc ...` or `python -m capstone.cli`
- **Unified imports:** `from documind import RAGPipeline, DocuMind`

You have now walked through all six phases. See [notebooks/README.md](README.md) for setup and [../README.md](../README.md) for Docker quick start.
""",
            },
        ],
    ),
]


def _cell(cell_type: str, source: str) -> dict:
    return {
        "cell_type": cell_type,
        "metadata": {},
        "source": source.splitlines(keepends=True),
        "outputs": [],
        "execution_count": None,
    }


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, cells in NOTEBOOKS:
        nb = {
            "cells": [_cell(c["type"], c["source"]) for c in cells],
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3",
                },
                "language_info": {
                    "name": "python",
                    "pygments_lexer": "ipython3",
                },
            },
            "nbformat": 4,
            "nbformat_minor": 5,
        }
        path = OUT / f"{name}.ipynb"
        path.write_text(json.dumps(nb, indent=1), encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
